### ISSUE TITLE
Problem when Adding Payment Method: Stripe Error Regarding Expired API Key

### ISSUE THREAD

**Issue by RexWzh** [neutrinoapp/neutrino#12]
Hi,

I would like to express my gratitude for the Neutrino app. It's helpful to access models through a single gateway and router, and with the automatic feature enhancing user experience.

However, I encountered an issue when attempting to add a payment method. An error message was displayed, indicating a problem with the Stripe API key:

```
Expired API Key provided: sk_live_...
```

A screenshot for reference:

![Stripe Error](https://github.com/neutrinoapp/neutrino/assets/62223937/662a39ff-e703-48f8-aad1-e56302e10c00)

Could you please investigate this matter? Thanks for your time and assistance.

**Comment by RexWzh** [comment]
After googling the error, like here: https://wordpress.org/support/topic/invalid-api-key-provided-sk_live_ubd4/, it appears the "Expired API Key provided: sk_live_..." error could stem from an issue with the Neutrinoapp Stripe API keys. Additionally, one of my friends encountered the same problem while performing the same operation. Could you please verify their configuration?

**Comment by mominayaan** [comment]
@RexWzh Hi thank you very much for pointing this error. It should be fixed now! Closing this issue.
